blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [path('', views.blog_index, name='index'),
               path('detail/<int:id>/', views.blog_detail, name='detail'),
               path('<category>/', views.blog_category, name='category'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [path('admin/', admin.site.urls),
               path('project/', include('project.urls')),
               path('blog/', include('blog.urls')), ]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/urls.py
from django.urls import path
from . import views

app_name = 'project'
urlpatterns = [
    path('', views.project_index, name='index'),
    path('detail/<int:id>', views.project_detail, name='detail'),
]

blog/models.py
from django.db import models


class Post(models.Model):
    title = models.CharField('제목', max_length=255)
    contents = models.TextField('내용')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    categories = models.ManyToManyField('Category', related_name='posts')

    def __str__(self):
        return self.title


class Category(models.Model):
    name = models.CharField(max_length=50)
    def __str__(self): return self.name

project/models.py
from django.db import models

# Create your models here.

from django.db import models


class Project(models.Model):
    title = models.CharField('타이틀', max_length=200)
    description = models.TextField('프로젝트 내용')
    tech = models.CharField('사용기술', max_length=100)
    image = models.ImageField('프로젝트 이미지', blank=True, null=True, upload_to='project')
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render
from .models import Post


def blog_index(request):
    posts = Post.objects.all().order_by('-created_at')
    context = {'posts': posts}
    return render(request, 'blog/blog_index.html', context)


def blog_detail(request, id):
    post = Post.objects.get(pk=id)
    context = {'post': post}
    return render(request, 'blog/blog_detail.html', context)


def blog_category(request, category):
    posts = Post.objects.filter(categories__name__contains=category).order_by(
    '-created_at')
    context = {'posts': posts, 'category': category}
    return render(request, 'blog/blog_category.html', context)

project/views.py
from django.shortcuts import render
from .models import Project

# Create your views here.

from django.shortcuts import render
from .models import Project


def project_index(request):
    projects = Project.objects.all().order_by('-created_at')
    context = {'projects': projects}
    return render(request, 'project/project_index.html', context)


def project_detail(request, id):
    project = Project.objects.get(pk=id)
    context = {'project': project}
    return render(request, 'project/project_detail.html', context)

templates/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/gh/moonspam/NanumSquare@1.0/nanumsquare.css">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% block title %} <title>MAIN</title> {% endblock %}
</head>
<body>
<section class="wrap"> <!-- header -->
    <header id="header">
        <div class="inner">
            <h1 class="logo">
                <a href="{% url 'project:index' %}">logo</a>
            </h1>
            <nav class="nav">
                <ul>
                    <li><a href="{% url 'project:index' %}">프로젝트</a></li>
                    <li><a href="{% url 'blog:index' %}">블로그</a></li>
                </ul>
            </nav>
        </div>
    </header> <!-- end header -->
    {% block content %} {% endblock %}
</section>
{% load static %}
<script src="{% static 'js/main.js' %}"></script>
</body>
</html>

templates/blog/blog_category.html
{% extends 'base.html' %} {% block title %}<title>{{ post.title }}</title>{% endblock %} {% block content %}
<section class="category-index">
    <div class="inner">
        <div class="title"><h2>#{{ category }}</h2> {% for post in posts %}
            <div class="category-list"><h4><a href="{% url 'blog:detail' post.id %}">{{ post.title }}</a></h4></div>
            {% endfor %}
        </div>
    </div>
</section> {% endblock %}

templates/blog/blog_detail.html
{% extends 'base.html' %} {% block title %}<title>{{ post.title }}</title>{% endblock %} {% block content %}
<section class="blog-detail">
    <div class="inner"><h2 class="title">{{ post.title }}</h2>
        <div class="date">
            <ul>
                <li>{{ post.created_at.date }}</li>
                {% for category in post.categories.all %}
                <li><a href="{% url 'blog:category' category.name %}">{{ category.name }}</a></li>
                {% endfor %}
            </ul>
        </div>
        <div class="contents"><p> {{ post.contents | linebreaks }} </p></div>
        <div class="go-list"><a href="{% url 'blog:index' %}">
            <button>목록으로</button>
        </a></div>
    </div>
</section> {% endblock %}

templates/blog/blog_index.html
{% extends 'base.html' %}
{% block title %}<title>블로그</title>{% endblock %}
{% block content %}
<section class="blog-index">
    <div class="inner">
        {% for post in posts %}
        <div class="date">
            <ul>
                <li><p>{{ post.created_at.date }}</p></li>
                {% for category in post.categories.all %}
                <li><a href="{% url 'blog:category' category.name %}">{{ category.name }}</a></li>
                {% endfor %}
            </ul>
        </div>
        <div class="title"><a href="{% url 'blog:detail' post.id %}"><h4>{{ post.title }}</h4>
            <p>{{ post.contents | slice:":200" }}...</p></a></div>
        {% endfor %}
    </div>
</section>
{% endblock %}

templates/project/project_detail.html
{% extends 'base.html' %} {% block title %}
<title>{{ project.title }} </title> {% endblock %} {% block content %} <!--project detail-->
<section class="project-detail">
    <div class="inner">
        <div class="detail">
            <div class="detail-img"><img src="{{ project.image.url }}" alt="{{ project.title }}" width="500px"></div>
            <div class="detail-content">
                <div class="title"><p>{{ project.title }}</p></div>
                <div class="tech"><p>{{ project.tech }}</p></div>
                <div class="description"><p>{{ project.description }}</p></div>
            </div>
        </div>
        <div class="list">
            <a href="{% url 'project:index' %}">
                <p class="list-btn">목록으로</p>
            </a>
        </div>
    </div>
</section> <!--end detail--> {% endblock %}

templates/project/project_index.html
{% extends 'base.html' %} {% block title %} <title>프로젝트</title> {% endblock %} {% block content %} <!--project-->
<section class="project">
    <div class="inner">
        <ul class="project-list">
            {% for item in projects %}
            <li>
                <div class="card">
                    <div class="card-inner"><a href="{% url 'project:detail' item.id %}">
                        <div class="card-img"><img src="{{ item.image.url }}" alt="{{ item.title }}" width="300px">
                        </div>
                        <div class="card-title"><p>{{ item.title }}</p></div>
                    </a></div>
                </div>
            </li>
            {% endfor %}
        </ul>
    </div>
</section> <!--end project--> {% endblock %}